import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Mail, MapPin, Download, ArrowDown, ExternalLink, Send, ChevronDown, BrainCircuit, Gauge, ChartNoAxesCombined, Database, GraduationCap, Phone } from 'lucide-react';
import './styles.css';

const Github = (props) => (
 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>
  <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
  <path d="M9 18c-4.51 2-5-2-7-2" />
 </svg>
);

const Linkedin = (props) => (
 <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>
  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4v-7a6 6 0 0 1 6-6z" />
  <rect width="4" height="12" x="2" y="9" />
  <circle cx="4" cy="4" r="2" />
 </svg>
);

const projects = [
  { id:'sql', eyebrow:'SAFE MULTI-AGENT RAG AND NATURAL-LANGUAGE-TO-SQL SYSTEM', title:'Self-Correcting SQL Agent', description:'Built a containerized multi-agent AI assistant that converts natural-language questions into embedding-based retrieval, SQL generation, execution, validation, and self-review workflows.', bullets:['Implemented a critic loop that recovered failed SQL queries within two retries on a 10-question evaluation set','Added read-only database access, SQL allowlisting, and prompt-injection filtering','Blocked destructive SQL and prompt-injection attempts in a manual red-team test'], tags:['Python','LangGraph','FastAPI','PostgreSQL','pgvector','MCP','Docker','RAG'], architecture:['User Question','Embedding Retrieval','SQL Generator','Read-Only PostgreSQL','Critic / Validator','Safe Answer'] },
  { id:'router', eyebrow:'INTELLIGENT MODEL ROUTING FOR COST, QUALITY, AND LATENCY', title:'Cost-Aware LLM Router', description:'Built an AI-driven LLM query-routing system that selects a small local model or larger hosted model based on task complexity.', bullets:['Reduced average inference cost by 38%','Reduced p95 latency by 45%','Kept judge-scored output quality within 2 points of a single-large-model baseline'], tags:['Python','FastAPI','vLLM','Redis','GPTQ','AWQ','Dynamic Batching','LLM Evaluation'], architecture:['Incoming Prompt','Complexity Classifier','Local Model OR Hosted Model','Redis Semantic Cache','Response'], metrics:[['COST','-38%'],['P95 LATENCY','-45%'],['QUALITY','within 2 pts']] },
  { id:'vlm', eyebrow:'EFFICIENT VISION-LANGUAGE MODEL ADAPTATION AND EVALUATION', title:'Parameter-Efficient VLM Fine-Tuning', description:'Benchmarked CLIP, BLIP, and ViLT for visual question answering, then fine-tuned BLIP using full fine-tuning, LoRA, and DoRA.', bullets:['Ran 10+ Weights & Biases-tracked experiments','LoRA retained performance within 2.5 percentage points of full fine-tuning','Reduced trainable parameters by 98%','Reduced peak VRAM by 38%'], tags:['Python','PyTorch','Hugging Face Transformers','CLIP','BLIP','ViLT','LoRA','DoRA'], architecture:['VQA Dataset','Base VLM','Fine-Tuning Method','Evaluation','Resource-Efficient Configuration'] },
  { id:'ev', eyebrow:'CONCURRENT, EVENT-DRIVEN RESERVATION BACKEND', title:'EV Charging Slot Reservation Platform', description:'Built a production-style reservation platform focused on transactional correctness, concurrency control, asynchronous workflows, and reliable backend integration.', bullets:['Concurrency handling and reservation consistency under contention','Transaction design for double-booking prevention','Redis caching for hot availability reads','Kafka-driven asynchronous workflows and backend reliability'], tags:['Java','Spring Boot','PostgreSQL','Redis','Kafka','Docker','REST APIs'] },
  { id:'forecast', eyebrow:'TIME-SERIES FORECASTING, ANOMALY DETECTION, AND KPI REPORTING', title:'Demand Forecasting and Operational Analytics', description:'Built analytics workflows for demand forecasting and operational monitoring using Python, Pandas, regression, time-series analysis, anomaly detection, and Power BI.', bullets:['Analyzed 50,000+ customer records','Achieved 85% demand accuracy','Reduced reporting time by 30%','Monitored 15+ operational KPIs'], tags:['Python','Pandas','SQL','Power BI','DAX','Regression','Time Series Forecasting','Anomaly Detection'] }
];

const skillGroups = [
 ['Programming',['Java','Python','SQL','Data Structures and Algorithms']],
 ['Backend and Systems',['Spring Boot','FastAPI','REST APIs','PostgreSQL','pgvector','Redis','Kafka','Docker','AWS','Distributed Systems','System Design']],
 ['Machine Learning',['PyTorch','Hugging Face Transformers','Scikit-learn','ONNX Runtime','Deep Learning','Model Evaluation','Feature Engineering']],
 ['LLMs and Generative AI',['LLMs','Generative AI','Agentic AI','NLP','LangChain','LangGraph','RAG','Embeddings','Vector Databases','Transformers','AI Agents','Prompt Engineering','Tool Calling','MCP','vLLM']],
 ['Data and Observability',['Pandas','NumPy','TimescaleDB','ETL Pipelines','MLflow','Prometheus','Power BI','DAX']],
 ['Developer Tools',['Git','CI/CD','Cursor','Claude Code','Codex','GitHub Copilot']]
];

function App(){
 const [openProject,setOpenProject]=useState('sql');
 const [form,setForm]=useState({name:'',email:'',message:''});
 const [status,setStatus]=useState('');
 const [selectedSkill,setSelectedSkill]=useState('');
 const submit=async(e)=>{e.preventDefault();setStatus('Sending…');try{const r=await fetch('http://localhost:5000/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setStatus(d.message||'Message sent.');if(r.ok)setForm({name:'',email:'',message:''});}catch{setStatus('Demo mode: connect the Express server to deliver messages.');}};
 return <div className="site">
  <header className="nav"><a className="brand" href="#home">shivani mahadik</a><nav>{['Home','About','Projects','Experience','Skills','Education','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><div className="social"><a href="https://www.linkedin.com" aria-label="LinkedIn"><Linkedin/></a><a href="https://github.com" aria-label="GitHub"><Github/></a><a href="mailto:shivanim042003@gmail.com" aria-label="Email"><Mail/></a></div></header>
  <main>
   <section id="home" className="hero section"><div className="hero-copy"><p className="kicker">MS in Computer Science, University of Minnesota · Expected May 2027</p><h1>Shivani Mahadik</h1><p className="role">Applied AI Engineer <span>|</span> Agentic AI <span>|</span> LLM Systems <span>|</span> Backend Engineering</p><p className="lead">I build reliable AI agents, retrieval systems, efficient LLM infrastructure, and production-ready backend services.</p><p className="location"><MapPin/> Minneapolis, MN</p><div className="actions"><a className="btn primary" href="#projects">View Projects <ArrowDown/></a><a className="btn" href="/resume.pdf" download><Download/> Download Resume</a><a className="text-link" href="#contact">Contact Me</a></div></div><div className="control-plane"><p className="kicker">AGENTIC CONTROL PLANE</p><div className="orbit"><div className="core">AI SYSTEM</div>{['Reason','Route','Deploy','Validate','Tool Call','Retrieve'].map((x,i)=><span className={'orbit-label l'+i} key={x}>{x}</span>)}<div className="orbit-line line1"/><div className="orbit-line line2"/><div className="orbit-line line3"/><div className="orbit-line line4"/><div className="orbit-line line5"/><div className="orbit-line line6"/></div><div className="metrics"><span>p95 latency ↓ 45%</span><span>Inference cost ↓ 38%</span><span className="orange">Prompt attacks blocked</span></div></div></section>
   <SectionLabel label="ABOUT" sub="ENGINEERING FOCUS"/><section id="about" className="content section about"><div/><div><h2>Engineering AI Systems<br/>That Hold Up in Production</h2><p>I am a computer science master's student focused on applied AI and backend engineering. I build LLM-powered systems that combine retrieval, orchestration, evaluation, safety, performance optimization, and reliable APIs. I enjoy turning emerging AI capabilities into measurable, maintainable software.</p><div className="focus-list">{[[BrainCircuit,'Agentic AI Systems','Multi-agent orchestration, tool calling, prompt guardrails, structured workflows, retries, and evaluation.'],[Gauge,'LLM Infrastructure','Model routing, local and hosted inference, caching, quantization, batching, latency optimization, and cost control.'],[ChartNoAxesCombined,'ML Evaluation and Fine-Tuning','Experiment tracking, failure-mode analysis, LoRA/DoRA fine-tuning, calibration, and resource-efficient model adaptation.'],[Database,'Backend and Data Systems','FastAPI, Spring Boot, PostgreSQL, Redis, Kafka, Docker, APIs, data pipelines, and reliable asynchronous workflows.']].map(([Icon,t,d])=><div className="focus-row" key={t}><Icon/><div><h3>{t}</h3><p>{d}</p></div><span className="expand">expand</span></div>)}</div></div></section>
   <SectionLabel label="PROJECTS" sub="FEATURED"/><section id="projects" className="content section projects"><div/><div><h2>Systems built end to end,<br/>with measured outcomes</h2><p>Each project below ships an architecture, a safety or performance constraint, and an evaluation method — not just a demo.</p>{projects.map(p=><article className="project" key={p.id}><div className="project-main"><p className="eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p>{p.description}</p><ul>{p.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><a href="#contact">View Case Study</a><a href="https://github.com"><Github/> GitHub</a>{p.id!=='ev'&&<a href="#contact"><ExternalLink/> Live Demo</a>}</div></div><div className="project-side"><p className="eyebrow">ARCHITECTURE</p><ol>{(p.architecture||[]).map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span>{a}</li>)}</ol>{p.metrics&&<div className="metric-grid">{p.metrics.map(([a,b])=><div key={a}><p>{a}</p><strong>{b}</strong></div>)}</div>}<button className="expand-button" onClick={()=>setOpenProject(openProject===p.id?'':p.id)}>{openProject===p.id?'collapse':'expand'} <ChevronDown/></button>{openProject===p.id&&<div className="case-note">Architecture and evaluation details are available in the case study. Connect the GitHub and live-demo links to your deployed projects.</div>}</div></article>)}</div></section>
   <SectionLabel label="EXPERIENCE"/><section id="experience" className="content section experience"><div/><div><h2>Applied work across<br/>analytics and ML engineering</h2><Experience title="GreenCell Mobility" role="Data Analyst Intern" date="Mumbai, India · Oct 2024 – Jan 2025" bullets={['Diagnosed customer churn drivers by analyzing 50,000+ customer records with Python and Pandas, informing a re-engagement strategy that improved customer retention by 12%.','Built Power BI dashboards with DAX for 15+ metrics and applied time-series forecasting, regression, and anomaly detection to achieve 85% demand accuracy and reduce reporting time by 30%.','Collaborated in Agile sprints with cross-functional teams to improve dashboard designs and decision quality.']}/><Experience title="Geeta Services" role="AI/ML & Python Intern" date="Mumbai, India · Jan 2024 – Apr 2024" bullets={['Developed automated Python data-processing tools and pipelines with data preparation, feature engineering, and model optimization, reducing operational effort by 60%.','Implemented a data-quality framework for schema validation and missing values, improving data accuracy by 20% and reducing analyst onboarding time by 40%.','Documented workflows and norms to strengthen analytics governance and knowledge transfer.']}/></div></section>
   <SectionLabel label="SKILLS"/><section id="skills" className="content section skills"><div/><div><h2>Tooling across agents,<br/>inference, backend, and data</h2><p>Select any technology to highlight the projects that use it.</p>{skillGroups.map(([group,items])=><div className="skill-row" key={group}><p>{group}</p><div>{items.map(s=><button className={selectedSkill===s?'selected':''} onClick={()=>setSelectedSkill(selectedSkill===s?'':s)} key={s}>{s}</button>)}</div></div>)}{selectedSkill&&<div className="skill-result">Selected: <strong>{selectedSkill}</strong> · Related work: {projects.filter(p=>p.tags.includes(selectedSkill)).map(p=>p.title).join(', ')||'Core engineering foundation'}</div>}</div></section>
   <SectionLabel label="EDUCATION"/><section id="education" className="content section education"><div/><div><h2>Academic background</h2><div className="edu"><GraduationCap/><div><h3>University of Minnesota</h3><p>Master of Science in Computer Science</p></div><span>Minneapolis, MN · 2025 – Expected May 2027</span></div><div className="edu"><GraduationCap/><div><h3>Vidyalankar Institute of Technology</h3><p>Bachelor of Engineering in Computer Engineering</p><b>CGPA: 9.6 / 10</b></div><span>Mumbai, India · 2021 – 2025</span></div></div></section>
   <SectionLabel label="CONTACT"/><section id="contact" className="content section contact"><div/><div><h2>Let's Build Reliable AI Systems</h2><p>I am interested in Applied AI Engineer, Machine Learning Engineer, Generative AI Engineer, and Software Engineer opportunities.</p><div className="contact-grid"><div><p className="eyebrow">DIRECT CHANNELS</p><p><Mail/> shivanim042003@gmail.com</p><p><Linkedin/> linkedin.com/in/shivani-mahadik-ab651123b</p><p><Phone/> +1 (763) 485-3185</p><p><MapPin/> Minneapolis, MN</p><a className="btn primary" href="mailto:shivanim042003@gmail.com"><Mail/> Email Me</a></div><form onSubmit={submit}><p className="eyebrow">SEND A MESSAGE</p><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><textarea required placeholder="Message" rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className="btn" type="submit"><Send/> Send Message</button>{status&&<small>{status}</small>}</form></div></div></section>
  </main><footer><div><strong>Shivani Mahadik</strong><p>Applied AI Engineer · Minneapolis, MN</p></div><div className="social"><a href="https://www.linkedin.com"><Linkedin/></a><a href="https://github.com"><Github/></a><a href="mailto:shivanim042003@gmail.com"><Mail/></a></div><p>© 2026 Shivani Mahadik</p></footer>
 </div>
}
function SectionLabel({label,sub}){return <div className="section-label"><span>{label}</span>{sub&&<small>{sub}</small>}</div>}
function Experience({title,role,date,bullets}){return <article className="experience-item"><div><h3>{title}</h3><p className="role">{role}</p></div><span>{date}</span><ul>{bullets.map(b=><li key={b}>{b}</li>)}</ul></article>}
createRoot(document.getElementById('root')).render(<App/>);
